spring:
  application:
    name: secure-notes
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:mysql://localhost:3306/secure_notes
    username: root
    password: July723!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  app:
    jwtSecret: mySecretKeyString5xh4156dfghn56g4dfbhn13251dfgcb
    jwtExpirationMs: 172800000

logging:
  level:
    org:
      springframework:
        security: DEBUG